# Generated by Django 2.2.2 on 2019-07-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coach_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_id', models.ManyToManyField(blank=True, null=True, related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Inactive', max_length=255)),
                ('score', models.FloatField()),
                ('phone', models.CharField(max_length=11)),
                ('mobile', models.CharField(max_length=11)),
                ('description', models.TextField()),
                ('sex', models.CharField(choices=[('مرد', 'man'), ('زن', 'woman')], default='مرد', max_length=32)),
                ('famous', models.CharField(choices=[('Number_one', 'number_one'), ('Number_two', 'number_two'), ('None', 'none')], default='None', max_length=32)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Area')),
                ('category_id', models.ManyToManyField(blank=True, null=True, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('day', models.CharField(choices=[('shanbe', 'shanbe'), ('yeshanbe', 'yeshanbe'), ('doshanbe', 'doshanbe'), ('seshanbe', 'seshanbe'), ('charshanbe', 'charshanbe'), ('panjshanbe', 'panjshanbe'), ('jome', 'jome'), ('simple', 'simple')], default='simple', max_length=255)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('price', models.TextField(default='')),
                ('sans', models.CharField(blank=True, choices=[('One', 'one'), ('two', 'two'), ('Three', 'three'), ('Four', 'four'), ('Five', 'five'), ('Six', 'six'), ('seven', 'seven'), ('Eight', 'eight'), ('Nine', 'nine'), ('Ten', 'ten'), ('Eleven', 'eleven'), ('Twelve', 'twelve')], max_length=32, null=True)),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.ManyToManyField(blank=True, null=True, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_expire', models.DateTimeField()),
                ('number_of_session', models.IntegerField()),
                ('price', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=64, null=True)),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Coach_Profile')),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
                ('hour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hour')),
            ],
        ),
        migrations.CreateModel(
            name='Training_Class_MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Training_Class')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('myuser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Role_MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Gym_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Facility')),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Gym_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Group_MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('date_start', models.DateTimeField()),
                ('date_expires', models.DateTimeField()),
                ('usage_limit', models.IntegerField()),
                ('minimum_amount', models.IntegerField()),
                ('users', models.TextField()),
                ('groups', models.TextField()),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('Show', 'show'), ('Hidden', 'hidden')], default='Hidden', max_length=255)),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='main.Province')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.City'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Reserved', 'reserved'), ('Not Paid', 'not paid'), ('Reserving', 'reserving'), ('Expired', 'expired')], default='Not Paid', max_length=32)),
                ('description', models.TextField()),
                ('order_date', models.DateField()),
                ('total_price', models.TextField()),
                ('paid_money', models.TextField()),
                ('coupon_price', models.TextField(blank=True, null=True)),
                ('coupon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Coupon')),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gym')),
                ('hour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hour')),
                ('myuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hour_id', 'order_date')},
            },
        ),
    ]
