# Generated by Django 2.2.2 on 2019-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='picture',
            field=models.ImageField(upload_to='gym_pictures/'),
        ),
    ]
