# Generated by Django 2.2.2 on 2019-07-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='groups',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='gym_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='gym_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='gym', to='main.Gym'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='users',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
