# Generated by Django 2.2.2 on 2019-07-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190727_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='groups',
        ),
        migrations.AddField(
            model_name='coupon',
            name='group_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='group', to='main.Group'),
        ),
    ]
