# Generated by Django 2.2.2 on 2019-07-28 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20190728_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='myuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
