# Generated by Django 2.2.2 on 2019-07-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190728_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='picture',
            field=models.ImageField(upload_to='gym_pictures/'),
        ),
    ]
