# Generated by Django 2.2.2 on 2019-07-29 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190728_1902'),
        ('main', '0005_auto_20190729_0119'),
    ]

    operations = [
    ]
