# Generated by Django 2.2.2 on 2019-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20190729_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach_profile',
            name='picture',
            field=models.ImageField(upload_to='coach_pictures/'),
        ),
        migrations.DeleteModel(
            name='Role_MyUser',
        ),
    ]
