# Generated by Django 2.2.2 on 2019-07-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190729_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach_profile',
            name='picture',
            field=models.ImageField(default='coach_pictures/avatar.png', upload_to='coach_pictures/'),
        ),
    ]
