# Generated by Django 2.2.2 on 2019-07-30 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20190729_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_class',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
