# Generated by Django 2.2.2 on 2019-07-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20190729_0139'),
        ('main', '0009_training_class_user_id'),
    ]

    operations = [
    ]
