# Generated by Django 2.2.2 on 2019-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20190730_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='main.Category'),
        ),
    ]
