# Generated by Django 2.2.2 on 2019-08-06 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_gym_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='myuser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
