# Generated by Django 2.2.2 on 2019-08-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190806_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_class',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_class', to='main.Coach_Profile'),
        ),
    ]
