# Generated by Django 2.2.2 on 2019-08-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190806_2059'),
        ('main', '0011_auto_20190805_2228'),
    ]

    operations = [
    ]
