# Generated by Django 2.2.2 on 2019-08-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190806_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach_profile',
            name='picture',
            field=models.ImageField(default='coach_pictures/avatar.png', height_field='500', upload_to='coach_pictures/', width_field='500'),
        ),
    ]
