# Generated by Django 2.2.2 on 2019-08-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190810_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach_profile',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='500', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='coach_profile',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='500', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='coach_profile',
            name='picture',
            field=models.ImageField(default='coach_pictures/avatar.png', height_field='image_height', upload_to='coach_pictures/', width_field='image_width'),
        ),
    ]
