# Generated by Django 2.2.2 on 2019-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190810_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach_profile',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='coach_profile',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='coach_profile',
            name='picture',
            field=models.ImageField(default='coach_pictures/avatar.png', upload_to='coach_pictures/'),
        ),
    ]
