# Generated by Django 2.2.2 on 2019-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_training_class_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_class',
            name='sex',
            field=models.CharField(choices=[('مرد', 'man'), ('زن', 'woman')], default='مرد', max_length=32),
        ),
    ]
