# Generated by Django 2.2.2 on 2019-08-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_training_class_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_class',
            name='picture',
            field=models.ImageField(default=1, upload_to='training-class-pic/'),
            preserve_default=False,
        ),
    ]
