# Generated by Django 2.2.2 on 2019-08-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_training_class_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_class',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
