# Generated by Django 2.2.2 on 2019-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190821_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='facility_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='facilities', to='main.Facility'),
        ),
    ]
