# Generated by Django 2.2.2 on 2019-08-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_gym_facility_id'),
        ('main', '0014_merge_20190808_1137'),
    ]

    operations = [
    ]
