# Generated by Django 2.2.2 on 2019-08-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_gym_facility_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
