# Generated by Django 2.2.2 on 2019-08-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190824_0916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together={('open', 'day')},
        ),
    ]
