# Generated by Django 2.2.2 on 2019-08-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190824_1048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together={('open', 'day', 'gym_id')},
        ),
    ]
