# Generated by Django 2.2.2 on 2019-08-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_merge_20190823_1045'),
        ('main', '0024_auto_20190824_1048'),
    ]

    operations = [
    ]
