# Generated by Django 2.2.2 on 2019-08-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_merge_20190825_0114'),
        ('main', '0025_auto_20190825_0118'),
    ]

    operations = [
    ]
