# Generated by Django 2.2.2 on 2019-08-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190825_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym_facility',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='gym_facility',
            name='gym_id',
        ),
        migrations.RemoveField(
            model_name='training_class_myuser',
            name='myuser_id',
        ),
        migrations.RemoveField(
            model_name='training_class_myuser',
            name='training_class_id',
        ),
        migrations.DeleteModel(
            name='Group_MyUser',
        ),
        migrations.DeleteModel(
            name='Gym_Facility',
        ),
        migrations.DeleteModel(
            name='Training_Class_MyUser',
        ),
    ]
