# Generated by Django 2.2.2 on 2019-08-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190825_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gym_Category',
        ),
    ]
