# Generated by Django 2.2.2 on 2019-08-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_gym_category'),
        ('main', '0026_merge_20190825_0119'),
    ]

    operations = [
    ]
