# Generated by Django 2.2.2 on 2019-08-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20190826_1202'),
        ('main', '0028_auto_20190828_1216'),
    ]

    operations = [
    ]
