# Generated by Django 2.2.2 on 2019-10-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_coupon_hour_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ticket')),
            ],
        ),
    ]
