# Generated by Django 2.2.2 on 2019-10-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20191024_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_room', to='main.Room'),
        ),
        migrations.DeleteModel(
            name='Reply_Ticket',
        ),
    ]
